# File: _config.yml
name: Jasmine Kim, Full Stack Developer
markdown: kramdown

baseurl: "https://jiminkk.github.io/gwc-curriculum" # the subpath of your site, e.g. /blog/
url: "https://jiminkk.github.io/gwc-curriculum" # the base hostname & protocol for your site
